config/routes.rb
Rails.application.routes.draw do
  get 'plays/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  match 'games/store_images' => 'games#store_images', via: %i[get post]
  post 'plays/create', to: 'plays#create'
  root to: 'games#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/play.rb
class Play < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'fileutils'

class GamesController < ApplicationController
  def index
    cookies[:image_urls] = nil
  end

  def store_images
    @image_urls = cookies[:image_urls] = img_public_paths if params[:image].present?
    @plays = Play.all
  end

  private

  def copy_file_to_public(image)
    tmp = image.tempfile
    file = File.join('public/games', image.original_filename)
    FileUtils.cp tmp.path, file
  end

  def img_public_paths
    Dir.mkdir('public/games') unless Dir.exist?('public/games')
    params[:image].each_with_object([]) do |image, image_urls|
      copy_file_to_public(image)
      image_urls << image.original_filename
    end
  end
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  skip_before_action :verify_authenticity_token, only:[:create]
  def create
    @play = Play.new(play_params)
    if @play.save
      respond_to do |format|
        format.json { render json: {url: @play.image_url, count: @play.counter} }
      end
    end
  end

  private

  def play_params
    params.permit(:image_url, :counter)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<h1>Home</h1>
<%= form_with url: games_store_images_path do |f| %>
  <%= f.label :image, "Image" %>
  <%= f.file_field :image, multiple: true %>

  <%= f.submit 'Submit' %>
<% end %>

app/views/games/store_images.html.erb
<h1 id="counter"></h1>
<img id="image" height="200px" width="200px">
<button onclick="savePlayData()" id="btn">Click!</button>
<br><br>
<table id="plays">
  <thead>
    <th>Image URL</th>
    <th>Counter</th>
  </thead>
  <tbody>
    <% if @plays.present? %>
      <% @plays.each do |play| %>
        <tr>
          <td><%= play.image_url %></td>
          <td><%= play.counter %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<%= render partial: 'image_counter_script' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageCountdown</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>